const INSTRUCTION_SET_INFO = {

    ADDRESSINGMODE:{
        url: [ADDRESSINGMODE_TEXT]
    },
    ADC:{
        url:[ADDITION_TEXT,REPRESENTATIONOFNUMBERS_TEXT,SIGNEDNUMBERARITHMATIC_TEXT]
    },
    AND:{
        url:[LOGICALINSTRUCTIONS_TEXT,AND_TEXT]
    },
    ASL:{
        url:[SHIFTANDROTATE_TEXT]
    },
    BCC:{
        url:[BRANCH_TEXT]
    },
    BCS:{
        url:[BRANCH_TEXT]
    },
    BEQ:{
        url:[BRANCH_TEXT]
    },
    BIT:{
        url:[BIT_TEXT]
    },
    BMI:{
        url:[BRANCH_TEXT]
    },
    BNE:{
        url:[BRANCH_TEXT]
    },
    BPL:{
        url:[BRANCH_TEXT]
    },
    BRK:{
        url:[INTERUPTS_TEXT]
    },
    BVC:{
        url:[BRANCH_TEXT]
    },
    BVS:{
        url:[BRANCH_TEXT]
    },
    CLC:{
        url:[CARRY_TEXT]
    },
    CLD:{
        url:[DECIMALMODE_TEXT,REPRESENTATIONOFNUMBERS_TEXT]
    },
    CLI:{
        url:[INTERUPTS_TEXT]
    },
    CLV:{
        url:[SIGNEDNUMBERARITHMATIC_TEXT]
    },
    CMP:{
        url:[COMPARE_TEXT]
    },
    CPX:{
        url:[COMPARE_TEXT]
    },
    CPY:{
        url:[COMPARE_TEXT]
    },
    DEC:{
        url:[INCREMENTANDDECREMENT_TEXT]
    },
    DEX:{
        url:[INCREMENTANDDECREMENT_TEXT]
    },
    DEY:{
        url:[INCREMENTANDDECREMENT_TEXT]
    },
    EOR:{
        url:[LOGICALINSTRUCTIONS_TEXT,XOR_TEXT]
    },
    INC:{
        url:[INCREMENTANDDECREMENT_TEXT]
    },
    INX:{
        url:[INCREMENTANDDECREMENT_TEXT]
    },
    INY:{
        url:[INCREMENTANDDECREMENT_TEXT]
    },
    JMP:{
        url:[JUMP_TEXT]
    },
    JSR:{
        url:[SUBROUTINE_TEXT]
    },
    LDA:{
        url:[LOADANDSTORE_TEXT]
    },
    LDX:{
        url:[LOADANDSTORE_TEXT]
    },
    LDY:{
        url:[LOADANDSTORE_TEXT]
    },
    LSR:{
        url:[SHIFTANDROTATE_TEXT]
    },
    NOP:{
        url:[NOP_TEXT]
    },
    ORA:{
        url:[LOGICALINSTRUCTIONS_TEXT,OR_TEXT]
    },
    PHA:{
        url:[STACK_TEXT]
    },
    PHP:{
        url:[STACK_TEXT]
    },
    PLA:{
        url:[STACK_TEXT]
    },
    PLP:{
        url:[STACK_TEXT]
    },
    ROL:{
        url:[SHIFTANDROTATE_TEXT]
    },
    ROR:{
        url:[SHIFTANDROTATE_TEXT]
    },
    RTI:{
        url:[INTERUPTS_TEXT]
    },
    RTS:{
        url:[SUBROUTINE_TEXT]
    },
    SBC:{
        url:[SUBTRACTION_TEXT,REPRESENTATIONOFNUMBERS_TEXT,SIGNEDNUMBERARITHMATIC_TEXT]
    },
    SEC:{
        url:[CARRY_TEXT]
    },
    SED:{
        url:[DECIMALMODE_TEXT,REPRESENTATIONOFNUMBERS_TEXT]
    },
    SEI:{
        url:[INTERUPTS_TEXT]
    },
    STA:{
        url:[LOADANDSTORE_TEXT]
    },
    STX:{
        url:[LOADANDSTORE_TEXT]
    },
    STY:{
        url:[LOADANDSTORE_TEXT]
    },
    TAX:{
        url:[TRANSFER_TEXT]
    },
    TAY:{
        url:[TRANSFER_TEXT]
    },
    TSX:{
        url:[TRANSFER_TEXT,STACK_TEXT]
    },
    TXA:{
        url:[TRANSFER_TEXT]
    },
    TXS:{
        url:[TRANSFER_TEXT,STACK_TEXT]
    },
    TYA:{
        url:[TRANSFER_TEXT]
    }
}