const INSTRUCTION_SET_INFO = {

    ADDRESSINGMODE:{
        url:['addressingmode.html']
    },
    ADC:{
        url:['addition.html','representationOfNumbers.html','signedNumberArithmetic.html']
    },
    AND:{
        url:['logicalInstructions.html','and.html']
    },
    ASL:{
        url:['shiftAndRotate.html']
    },
    BCC:{
        url:['branch.html']
    },
    BCS:{
        url:['branch.html']
    },
    BEQ:{
        url:['branch.html']
    },
    BIT:{
        url:['bit.html']
    },
    BMI:{
        url:['branch.html']
    },
    BNE:{
        url:['branch.html']
    },
    BPL:{
        url:['branch.html']
    },
    BRK:{
        url:['interupts.html']
    },
    BVC:{
        url:['branch.html']
    },
    BVS:{
        url:['branch.html']
    },
    CLC:{
        url:['carry.html']
    },
    CLD:{
        url:['decimalMode.html','representationOfNumbers.html']
    },
    CLI:{
        url:['interupts.html']
    },
    CLV:{
        url:['signedNumberArithmetic.html']
    },
    CMP:{
        url:['compare.html']
    },
    CPX:{
        url:['compare.html']
    },
    CPY:{
        url:['compare.html']
    },
    DEC:{
        url:['incrementAndDecrement.html']
    },
    DEX:{
        url:['incrementAndDecrement.html']
    },
    DEY:{
        url:['incrementAndDecrement.html']
    },
    EOR:{
        url:['logicalInstructions.html','xor.html']
    },
    INC:{
        url:['incrementAndDecrement.html']
    },
    INX:{
        url:['incrementAndDecrement.html']
    },
    INY:{
        url:['incrementAndDecrement.html']
    },
    JMP:{
        url:['jump.html']
    },
    JSR:{
        url:['subroutine.html']
    },
    LDA:{
        url:['loadAndStore.html']
    },
    LDX:{
        url:['loadAndStore.html']
    },
    LDY:{
        url:['loadAndStore.html']
    },
    LSR:{
        url:['shiftAndRotate.html']
    },
    NOP:{
        url:['nop.html']
    },
    ORA:{
        url:['logicalInstructions.html','or.html']
    },
    PHA:{
        url:['stack.html']
    },
    PHP:{
        url:['stack.html']
    },
    PLA:{
        url:['stack.html']
    },
    PLP:{
        url:['stack.html']
    },
    ROL:{
        url:['shiftAndRotate.html']
    },
    ROR:{
        url:['shiftAndRotate.html']
    },
    RTI:{
        url:['interupts.html']
    },
    RTS:{
        url:['subroutine.html']
    },
    SBC:{
        url:['subtraction.html','representationOfNumbers.html','signedNumberArithmetic.html']
    },
    SEC:{
        url:['carry.html']
    },
    SED:{
        url:['decimalMode.html','representationOfNumbers.html']
    },
    SEI:{
        url:['interupts.html']
    },
    STA:{
        url:['loadAndStore.html']
    },
    STX:{
        url:['loadAndStore.html']
    },
    STY:{
        url:['loadAndStore.html']
    },
    TAX:{
        url:['transfer.html']
    },
    TAY:{
        url:['transfer.html']
    },
    TSX:{
        url:['transfer.html','stack.html']
    },
    TXA:{
        url:['transfer.html']
    },
    TXS:{
        url:['transfer.html','stack.html']
    },
    TYA:{
        url:['transfer.html']
    }
}